spring:
    application:
        name: demo-vtp-mic
    datasource:
        hikari:
            connection-timeout: 30000
            idle-timeout: 600000
            max-lifetime: 1800000
            maximum-pool-size: 10
            minimum-idle: 5
        password: 123
        url: jdbc:mysql://localhost:3306/db-vtp?createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true

application:
    security:
        jwt:
            expiration: 3600000
            secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

